<?php

/**
 * August Ash Demo Ribbon Module
 *
 * @author Peter McWilliams <pmcwilliams@augustash.com>
 * @license MIT
 */

declare(strict_types=1);

use Augustash\DemoRibbon\ViewModel\RibbonNotice;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var RibbonNotice $viewModel */

$viewModel = $block->getData('view_model');
$classes = \sprintf(
    '%s %s',
    $viewModel->getDemoLocation(),
    $viewModel->getDemoSize(),
);
?>
<?php if ($viewModel->displayDemoNotice()): ?>
    <div class="message global demo-ribbon">
        <a href="/"
           class='ribbon <?= $escaper->escapeHtmlAttr($classes) ?>'>
           <?= $escaper->escapeHtml($viewModel->getDemoMessage()) ?>
        </a>
    </div>
<?php endif; ?>
