<?php
/**
 * August Ash Demo Ribbon
 *
 * @author    Peter McWilliams <pmcwilliams@augustash.com>
 * @copyright 2019 August Ash, Inc.
 */
?>
<?php
/**
 * @var \Augustash\DemoRibbon\Block\Html\Notices $block
 */
?>
<?php if ($block->displayNoscriptNotice()): ?>
    <noscript>
        <div class="message global noscript">
            <div class="content">
                <p>
                    <strong><?= /* @escapeNotVerified */ __('JavaScript seems to be disabled in your browser.') ?></strong>
                    <span><?= /* @escapeNotVerified */ __('For the best experience on our site, be sure to turn on Javascript in your browser.') ?></span>
                </p>
            </div>
        </div>
    </noscript>
<?php endif; ?>
<?php if ($block->displayNoLocalStorageNotice()): ?>
    <div class="notice global site local_storage" style="display: none;">
        <div class="content">
            <p>
                <strong><?= /* @escapeNotVerified */ __('Local Storage seems to be disabled in your browser.') ?></strong><br />
                <?= /* @escapeNotVerified */ __('For the best experience on our site, be sure to turn on Local Storage in your browser.') ?>
            </p>
        </div>
    </div>
    <script>
        require(['jquery'], function(jQuery){
            // <![CDATA[
            (function($) {
                var test = 'test';
                try {
                    localStorage.setItem(test, test);
                    localStorage.removeItem(test);
                } catch(e) {
                    $(".notice.global.site.local_storage").show();
                }
            })(jQuery);
            // ]]>
        });
    </script>
<?php endif; ?>
<?php if ($block->displayDemoNotice()): ?>
    <div class="message global demo-ribbon">
        <a href="/" class='ribbon <?= $block->getDemoLocation() ?> <?= $block->getDemoSize() ?>'><?= $block->escapeHtml($block->getDemoMessage()) ?></a>
    </div>
<?php endif; ?>
