<?php

/**
 * August Ash Demo Ribbon Module
 *
 * @author Peter McWilliams <pmcwilliams@augustash.com>
 * @license MIT
 */

declare(strict_types=1);

use Augustash\DemoRibbon\ViewModel\RibbonNotice;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var RibbonNotice $viewModel */

$viewModel = $block->getData('view_model');
?>
<?php if ($viewModel->displayDemoNotice()): ?>
    <div class="messages">
        <div class="message message-note message-demo-mode">
            <?= $escaper->escapeHtml($viewModel->getDemoMessage()) ?> -
            <?= $escaper->escapeHtml(__('You can browse and place orders, but nothing will be honored.')) ?>
        </div>
    </div>
<?php endif; ?>
